services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.5
    container_name: keycloak
    command:
      [ "start-dev", "--import-realm" ]
    ports:
      - 8080:8080
      - 8443:8443
      - 9000:9000
    env_file:
      - .env
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
